# Generated by Django 5.2.9 on 2025-12-15 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntaje',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='puntaje',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='puntaje',
            name='usuario_temporal',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idiomaPreferido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.PositiveIntegerField()),
                ('accuracy', models.PositiveIntegerField()),
                ('errors', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Texto',
        ),
        migrations.DeleteModel(
            name='Puntaje',
        ),
        migrations.DeleteModel(
            name='UsuarioTemporal',
        ),
    ]
